### ISSUE TITLE
TODO hackday

### ISSUE THREAD

**Issue by gre** [gre/diaporama-editor#1]
## Editor

**An editor to create a new slideshow.**
- [x] Drag & Drop photos
- [x] Upload Button which upload photos to imgur
- [ ] a Timeline interface to reorganize photos order
  - [ ] define the duration that an image stay : globally / per image?
- [ ] customize Transition between each images
  - [ ] select box to change the transition
  - [ ] define the duration of the transition
  - [ ] custom uniforms (bonus)
  - [ ] easings (bonus)
- [ ] being able to define an soundcloud music
- [x] Save the final slideshow to a server (ours?)
- [ ] URL to the viewer
## Viewer

**A standalone viewer which renders a slideshow.**
- [x] Render the images
- [x] Perform transitions between images
- [x] support soundcloud music
